Image dataset
Scyfer/fuel pull request #18
Opened 2016-10-19 15:06 UTC by markusnagel

Added a new dataset which directly reads images from file. This is useful for data which is not frequently/recurrently used since it saves the need to convert it before to h5py. As input it expects a regular expression which gives great flexibility on how the images can be arranged on disk.

2016-10-19 15:12 UTC, aukejw commented on fuel/datasets/image.py
> +    load_in_memory: bool, default=True
don't forget to surround the ':' with spaces

2016-10-19 15:18 UTC, aukejw requested changes
Tests are missing, other than that some minor comments.

2016-10-19 15:18 UTC, aukejw commented on fuel/datasets/image.py
> +    load_in_memory: bool, default=True
don't forget to surround the ':' with spaces!

2016-10-19 15:18 UTC, aukejw commented on fuel/datasets/image.py
> +        give the source ``fiel_paths`` which contains the exact path of
Typo `fiel_paths`

2016-10-19 15:18 UTC, aukejw commented on fuel/datasets/image.py
> +def _list_fancy_indexing(iterable, request):
Can you add a docstring? Its purpose is not immediately clear from the name of the method.

2016-10-20 15:07 UTC, aukejw approved these changes

2016-10-24 13:22 UTC, aukejw requested changes
Didn't notice it before, but the tests do not actually check whether the right thing is returned.

2016-10-24 13:22 UTC, aukejw commented on tests/test_image_dataset.py
> +        for imgs, _ in stream.get_epoch_iterator():
Final remark: can you assert that the contents of the image_path source match the dummy image paths? We now know that the batch and its content are of the correct shape, but not that it actually contains the images we were looking for..

2016-10-24 13:22 UTC, aukejw commented on tests/test_image_dataset.py
> +        for imgs, _ in stream.get_epoch_iterator():
And here as well, of course.

2016-10-24 13:30 UTC, markusnagel commented on tests/test_image_dataset.py
> +        for imgs, _ in stream.get_epoch_iterator():
Well having the correct number of images and the correct shape is a very strong indicator that we loaded the correct dataset. But I can check the 'image_paths' for the reason that that gets correctly set.

2016-10-24 13:32 UTC, aukejw commented on tests/test_image_dataset.py
> +        for imgs, _ in stream.get_epoch_iterator():
Please do, then we're certain that it's not the exact same image path being returned X times.

2016-10-24 13:56 UTC, aukejw commented on tests/test_image_dataset.py
> +            assert self.ds_path in file_paths[0]
Why not `assert all(file_path in dummy_image_paths for image_path in file_paths)`? I understand that you don't want to test whether glob works, but given that there is a custom function `_list_fancy_indexing` in between it wouldn't hurt to actually check the correctness of the output.

2016-10-24 14:40 UTC, aukejw approved these changes

2016-10-24 14:41 UTC, merged